---
title: "FINAL ASSIGNMENT"
author: "Shivadarshini Sreekanth"
date: "2026-03-16"
output: 
 rmdformats::readthedown:
    self_contained: true
    highlight: "default"
    thumbnails: false
    fig_width: 7
    fig_height: 5
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Cleaning & Handling Missingness

```{r message=FALSE, warning=FALSE}
#libraries
library(tidyverse)
library(randomForest)
library(gbm)
library(pROC)
library(tidyr)
library(ggplot2)
```

```{r}
#reading data
stroke_data <- read.csv("stroke.csv", na.strings = c("N/A", "NA", ""))
```

```{r}
head(stroke_data)
str(stroke_data)
dim(stroke_data)
```

```{r}
#removing ID column
stroke_data <- stroke_data %>%
  select(-id)
```

```{r}
#converting variables
stroke_data <- stroke_data %>%
  mutate(
    gender = as.factor(gender),
    hypertension = as.factor(hypertension),
    heart_disease = as.factor(heart_disease),
    ever_married = as.factor(ever_married),
    work_type = as.factor(work_type),
    Residence_type = as.factor(Residence_type),
    smoking_status = as.factor(smoking_status),
    stroke = as.factor(stroke)
  )
#bmi to numeric
stroke_data$bmi <- as.numeric(stroke_data$bmi)
```

```{r}
#missing values
missing_count <- colSums(is.na(stroke_data))
missing_percent <- round(colMeans(is.na(stroke_data)) * 100, 2)

missing_summary <- data.frame(
  Variable = names(stroke_data),
  Missing_Count = missing_count,
  Missing_Percent = missing_percent
)
missing_summary
```

```{r}
#imputing missing BMI using median
median_bmi <- median(stroke_data$bmi, na.rm = TRUE)
stroke_data$bmi[is.na(stroke_data$bmi)] <- median_bmi
```

```{r}
#missing values check after imputing 
missing_count <- colSums(is.na(stroke_data))
missing_percent <- round(colMeans(is.na(stroke_data)) * 100, 2)

missing_summary <- data.frame(
  Variable = names(stroke_data),
  Missing_Count = missing_count,
  Missing_Percent = missing_percent
)
missing_summary
```

# Train & Test Data Split

```{r}
set.seed(123)
```

```{r}
#70-30
train_index <- sample(1:nrow(stroke_data), size = 0.7 * nrow(stroke_data))
```

```{r}
#training data
train_data <- stroke_data[train_index, ]
dim(train_data)

#testing data
test_data  <- stroke_data[-train_index, ]
dim(test_data)
```
```{r}
#class distribution
table(stroke_data$stroke)

#class distribution in training data
table(train_data$stroke)

#class distribution in testing data
table(test_data$stroke)
```

# Logistic Regression Model

```{r}
# Fit LRM
model_log <- glm(stroke ~ ., data = train_data, family = "binomial")
summary(model_log)

# Predict probabilities on test data
pred_prob_log <- predict(model_log, newdata = test_data, type = "response")

# Converting probabilities to class (0/1) using 0.5 threshold
pred_class_log <- ifelse(pred_prob_log > 0.2, 1, 0)
```

```{r}
#confusion matrix
cm_log_standard <- table(
  Predicted = factor(pred_class_log, levels = c(1, 0)),
  Actual = factor(test_data$stroke, levels = c(1, 0))
)
cm_log_standard
```

# Random Forest Model

```{r}
# Fit RFM
model_rf <- randomForest(stroke ~ ., data = train_data, ntree = 100)
print(model_rf)

# Predict probabilities on test data
pred_prob_rf <- predict(model_rf, newdata = test_data, type = "prob")[,2]

# Converting class
pred_class_rf <- ifelse(pred_prob_rf > 0.2, 1, 0)
pred_class_rf <- as.factor(pred_class_rf)
```

```{r}
# Confusion matrix
cm_rf_standard <- table(
  Predicted = factor(pred_class_rf, levels = c(1, 0)),
  Actual = factor(test_data$stroke, levels = c(1, 0))
)
cm_rf_standard
```

# Gradient Boosting Model

```{r}
train_gbm <- train_data
test_gbm  <- test_data

train_gbm$stroke <- as.numeric(as.character(train_gbm$stroke))
test_gbm$stroke  <- as.numeric(as.character(test_gbm$stroke))

# Fit GBM
model_gbm <- gbm(stroke ~ .,data = train_gbm, distribution = "bernoulli", n.trees = 100,
  interaction.depth = 3, shrinkage = 0.01, n.minobsinnode = 10, verbose = FALSE)

# predict probabilities
pred_prob_gbm <- predict(model_gbm, newdata = test_gbm, n.trees = 100, type = "response")

# convert probabilities to class
pred_class_gbm <- ifelse(pred_prob_gbm > 0.2, 1, 0)
```

```{r}
# confusion matrix
cm_gbm_standard <- table(
  Predicted = factor(pred_class_gbm, levels = c(1, 0)),
  Actual = factor(test_gbm$stroke, levels = c(1, 0))
)

cm_gbm_standard
```

# Model Comparison

```{r}
#Logistic Regression 
TP_log <- cm_log_standard["1","1"]
FP_log <- cm_log_standard["1","0"]
FN_log <- cm_log_standard["0","1"]
TN_log <- cm_log_standard["0","0"]

accuracy_log <- (TP_log + TN_log) / sum(cm_log_standard)
sensitivity_log <- TP_log / (TP_log + FN_log)
specificity_log <- TN_log / (TN_log + FP_log)

auc_log <- auc(roc(test_data$stroke, pred_prob_log))

accuracy_log
sensitivity_log
specificity_log
auc_log
```

```{R}
#Random Forest 
TP_rf <- cm_rf_standard["1","1"]
FP_rf <- cm_rf_standard["1","0"]
FN_rf <- cm_rf_standard["0","1"]
TN_rf <- cm_rf_standard["0","0"]

accuracy_rf <- (TP_rf + TN_rf) / sum(cm_rf_standard)
sensitivity_rf <- TP_rf / (TP_rf + FN_rf)
specificity_rf <- TN_rf / (TN_rf + FP_rf)

auc_rf <- auc(roc(test_data$stroke, pred_prob_rf))

accuracy_rf
sensitivity_rf
specificity_rf
auc_rf
```

```{r}
#Gradient Boosting
TP_gbm <- cm_gbm_standard["1","1"]
FP_gbm <- cm_gbm_standard["1","0"]
FN_gbm <- cm_gbm_standard["0","1"]
TN_gbm <- cm_gbm_standard["0","0"]

accuracy_gbm <- (TP_gbm + TN_gbm) / sum(cm_gbm_standard)
sensitivity_gbm <- TP_gbm / (TP_gbm + FN_gbm)
specificity_gbm <- TN_gbm / (TN_gbm + FP_gbm)

auc_gbm <- auc(roc(test_gbm$stroke, pred_prob_gbm))

accuracy_gbm
sensitivity_gbm
specificity_gbm
auc_gbm
```

```{r}
model_comparison <- data.frame(
  Model = c("Logistic Regression", "Random Forest", "Gradient Boosting"),
  Accuracy = c(accuracy_log, accuracy_rf, accuracy_gbm),
  Sensitivity = c(sensitivity_log, sensitivity_rf, sensitivity_gbm),
  Specificity = c(specificity_log, specificity_rf, specificity_gbm),
  AUC = c(as.numeric(auc_log), as.numeric(auc_rf), as.numeric(auc_gbm))
)
model_comparison
```

```{r}
comparison_long <- model_comparison %>%
  pivot_longer(
    cols = c(Accuracy, Sensitivity, Specificity, AUC),
    names_to = "Metric",
    values_to = "Value"
  )
ggplot(comparison_long, aes(x = Metric, y = Value, fill = Model)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Comparison of Prediction Model Performance",
    x = "Performance Metric",
    y = "Value"
  ) +
  theme_minimal()
```






